services:
  backend:
    image: lsingodiya/mern-backend:${IMAGE_TAG}
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

  frontend:
    image: lsingodiya/mern-frontend:${IMAGE_TAG}
    ports:
      - "80:3000"
    depends_on:
      - backend
